/**
 * Sample Mastermind-style events for the demo.
 */
export const sampleEvents = [
  {
    type: "message_received",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:00.000Z",
    surface: "chat",
    content_type: "text",
    content_preview: "What's the weather in San Francisco today?",
  },
  {
    type: "state_changed",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:00.050Z",
    from: "acknowledged",
    to: "running",
    reason: "Message received",
  },
  {
    type: "intent_classified",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:00.120Z",
    classification: {
      intent_type: "information_lookup",
      confidence: 0.94,
      needs_research: false,
      is_fast_path: true,
    },
  },
  {
    type: "brain_stage_started",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:00.200Z",
    stage: "executor",
    input_summary: "Fast-path tool execution for weather lookup",
  },
  {
    type: "llm_request_started",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:00.250Z",
    stage: "executor",
    model: "claude-sonnet-4-5-20250514",
    prompt_summary: "Execute weather lookup for San Francisco",
    tool_count: 5,
  },
  {
    type: "llm_response_received",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:01.800Z",
    stage: "executor",
    model: "claude-sonnet-4-5-20250514",
    response_summary: "Selected weather_lookup tool",
    tool_calls_count: 1,
    duration_ms: 1550,
  },
  {
    type: "tool_triggered",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:01.850Z",
    tool_name: "weather_lookup",
    run_id: "run-weather-001",
    inputs: { location: "San Francisco, CA", units: "fahrenheit" },
  },
  {
    type: "tool_completed",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:02.400Z",
    tool_name: "weather_lookup",
    run_id: "run-weather-001",
    success: true,
    result_summary: "72°F, partly cloudy, wind 12mph NW",
    duration_ms: 550,
  },
  {
    type: "brain_stage_completed",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:02.500Z",
    stage: "executor",
    output_summary: "Weather data retrieved successfully",
    duration_ms: 2300,
  },
  {
    type: "response_generated",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:02.600Z",
    text_length: 145,
    has_surface_actions: false,
    triggered_skills_count: 0,
    auto_generated: false,
  },
  {
    type: "state_changed",
    execution_id: "exec-001",
    turn_id: "turn-1",
    timestamp: "2026-04-20T10:00:02.650Z",
    from: "running",
    to: "completed",
    reason: "Response delivered",
  },
  // Second turn — with parallel tool calls
  {
    type: "message_received",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:10.000Z",
    surface: "chat",
    content_type: "text",
    content_preview: "Compare weather in SF, NYC, and London",
  },
  {
    type: "brain_stage_started",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:10.200Z",
    stage: "executor",
    input_summary: "Multi-city weather comparison",
  },
  {
    type: "llm_request_started",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:10.300Z",
    stage: "executor",
    model: "claude-sonnet-4-5-20250514",
    prompt_summary: "Compare weather across 3 cities",
    tool_count: 5,
  },
  {
    type: "llm_response_received",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:11.500Z",
    stage: "executor",
    model: "claude-sonnet-4-5-20250514",
    response_summary: "Selected 3 parallel weather_lookup calls",
    tool_calls_count: 3,
    duration_ms: 1200,
  },
  // Three parallel tool calls (within 50ms of each other)
  {
    type: "tool_triggered",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:11.550Z",
    tool_name: "weather_lookup",
    run_id: "run-sf-002",
    inputs: { location: "San Francisco, CA" },
  },
  {
    type: "tool_triggered",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:11.560Z",
    tool_name: "weather_lookup",
    run_id: "run-nyc-002",
    inputs: { location: "New York, NY" },
  },
  {
    type: "tool_triggered",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:11.570Z",
    tool_name: "weather_lookup",
    run_id: "run-london-002",
    inputs: { location: "London, UK" },
  },
  {
    type: "tool_completed",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:12.100Z",
    tool_name: "weather_lookup",
    run_id: "run-sf-002",
    success: true,
    result_summary: "72°F, partly cloudy",
    duration_ms: 550,
  },
  {
    type: "tool_completed",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:12.300Z",
    tool_name: "weather_lookup",
    run_id: "run-nyc-002",
    success: true,
    result_summary: "58°F, overcast",
    duration_ms: 740,
  },
  {
    type: "tool_completed",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:12.500Z",
    tool_name: "weather_lookup",
    run_id: "run-london-002",
    success: true,
    result_summary: "52°F, rain",
    duration_ms: 930,
  },
  {
    type: "brain_stage_completed",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:12.600Z",
    stage: "executor",
    output_summary: "All 3 city lookups completed",
    duration_ms: 2400,
  },
  {
    type: "response_generated",
    execution_id: "exec-001",
    turn_id: "turn-2",
    timestamp: "2026-04-20T10:00:12.700Z",
    text_length: 320,
    has_surface_actions: false,
    triggered_skills_count: 0,
    auto_generated: false,
  },
];
